### ISSUE TITLE
App sizing causing over scroll.

### ISSUE THREAD

**Issue by Deohgu** [Deohgu/minesweeper#13]
At the 800px width there is a media query that changes the app size causing its general size to be larger than the screen.

The app should resize without the need for extra space and be centred.
Have a look at the general sizing of the app and see if it makes sense.

**Comment by tshlos** [comment]
Hi, it's my first time trying to contribute to an open-source. Can I work on this issue?

**Comment by Deohgu** [comment]
Hello. Yes, that would be great. I've just contributed to my first open-source project recently as well!
If you find anything else that ought to be improved feel free to open an issue.
I'm also in the process of refactoring the whole code.

**Comment by svatsdev** [comment]
First time on opensource. Seems I have worked on this kind of problem when working on my 404 error page. will give a try.

**Comment by Deohgu** [comment]
> First time on opensource. Seems I have worked on this kind of problem when working on my 404 error page. will give a try.

Hey @svatsdev, seems like tshlos already intends on working on this issue.
If you want to contribute you can perhaps have a look at another issue labelled as "good first issue".

**Comment by svatsdev** [comment]
Okay sure
